version: '3.8'

services:
  app:
    build: .
    container_name: "api-server"
    command: sh -c "npm run
     migrate && npm start"
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app  
    links:
      - db
    depends_on:
      - db
    environment: 
      DB_HOST: host.docker.internal
      DB_USER: postgres
      DB_PASS: postgres   
  db:
    image: postgres:alpine
    container_name: api-db
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=postgres
networks: 
  overlay:
